@startuml
skinparam linetype ortho



node "Cliente\n(Navegador Web o App Móvil JME)" as Cliente

node "Proxy Gateway\ninscripciones.universidad.mx" as Proxy {
  artifact "Sistema de Autenticación\n(SSO Centralizado)"
}


node "Servidor de Aplicaciones Alumno 1\ninscripcionesalum1.universidad.mx" as Alum1 {
  artifact "App Web Alumno (PHP)"
  artifact "Servicios REST"
}

node "Servidor de Aplicaciones Alumno 2\ninscripcionesalum2.universidad.mx" as Alum2 {
  artifact "App Web Alumno (PHP)"
  artifact "Servicios REST"
}

node "Servidor de Aplicaciones Alumno 3\ninscripcionesalum3.universidad.mx" as Alum3 {
  artifact "App Web Alumno (PHP)"
  artifact "Servicios REST"
}



node "Servidor BackOffice\ninscripcionesbackoffice.universidad.mx" as Backoffice {
  artifact "App Gestión (PHP)"
  artifact "Servicios REST"
}



node "Servidor de Apps Alumnos\naplicacionesalumnos.universidad.mx" as AppAlumnos {
  artifact "App Móvil JME (Alumno)"
}

node "Servidor de Apps Empleados\naplicacionesempleados.universidad.mx" as AppEmpleados {
  artifact "App Móvil Backoffice"
  artifact "App Móvil Management"
}

database "BD \ninscripcionesdatos1.universidad.mx" as DB1
database "BD \ninscripcionesdatos2.universidad.mx" as DB2
database "BD \ninscripcionesdatos3.universidad.mx" as DB3




' Conexiones


Cliente --> Proxy : HTTPS Web / Móvil 
Proxy -left-> AppAlumnos
Proxy -right-> AppEmpleados
Proxy -down-> Alum1 : Balanceo
Proxy -down-> Alum2 : Balanceo
Proxy -down-> Alum3 : Balanceo
Proxy --> Backoffice : Gestión

Alum1 --> DB1
Alum2 --> DB2
Alum3 --> DB3
Backoffice -->DB3




@enduml